---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: service-injector
  name: service-injector
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 443
    targetPort: 8443
  selector:
    control-plane: service-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: service-injector
  name: service-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: service-injector
  template:
    metadata:
      labels:
        control-plane: service-injector
    spec:
      containers:
      - image: oam-dev/service-injector:v1
        name: manager
        command:
        - /app/manager
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        ports:
        - containerPort: 8443
          name: webhook
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-ns-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: service-injector
  labels:
    app: service-injector
webhooks:
  - name: service-injector.default.svc.cluster.local
    clientConfig:
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EUXhOREEwTURFd01Wb1hEVEk1TURReE1qQTBNREV3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHlKCnJPZHNwejN2aElPTUZQc3pGUEhkV3JIVXB3clZQamVkTEZmTzFPMmRNTUtyUUxOUU5XTVNYU3M5enY3Vjc5UWMKSWtwR056MFk5ald4UExiVjhBK1lVRDhqL1BQWGptMU5sRlhqalhhWVZaSlNHNnZPQy84QmYySDBvNG1Mek9BWQpmSG5FK0JxOXBHMlNBSTloZS9GY3FNN3p1T1B3R21FNk5FVCt1bWgxRmNVRGYwQVMrbS9JRXhjVnp4alhCdlpBCjlkSWtncVpLLzFxWVRSUW9SVWhVNVBOSjFWUjVkc1NjZFl6NmtBb1Q1OC9zNG9uYWtGcG9RRUFkVEljeVZNZ2MKWnhHRDRWWnNSNFZkLzZwTEhvbnBoVXNZenF1dDN0bE5KWlA4c1drVW5iTElDRk9oZ1NGQzNYaGNHS3lxcWxadApQc1dhbXJXdDhKYWJPQjY4bnFjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCbmprOGhrdXJGZVV5T2hOSXVVN2t6YnlTcGZ0NmhKS3ZxdkNwZmNIUHEvM1doMndUWApwMmhucEJuSVJ5TWtNbHdrR0dIWDU3VTNpV2ZlTDhzMm5XeE12SjZJRlFmUm5vK1VicUdFdmozRVBib0RHSU1HCnMvMFhCUjJIcy9KSVVnc0RscFlRL2tYd2dJWEZaT1ZwY0J0RDJRdk96S0dKVGxyTzREVzZEQS9ZUy9Bd1hzSnMKSm42VVl6YjNrY1diMFU3MG1QaTl2UzBRYk5MZmVLL1dmRTc4dUpGK3JxYzdVUzZ2VjU1blFHWU5OelpsWk9TTwoxUENPYzA1THlzYnVvZy9rYUNOOEFDL3hTL1J5cTFGdUtHb01kOTJsb29obmMwUmNlWHBkTy9KazZsMVVwVkY4Cnh6aXhEZGZQcS9HNzhIQjZtL2RvSHU3QjZENFFlOEtkb08wVwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: service-injector
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]


