---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: service-injector
  name: service-injector
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 443
    targetPort: 8443
  selector:
    control-plane: service-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: service-injector
  name: service-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: service-injector
  template:
    metadata:
      labels:
        control-plane: service-injector
    spec:
      containers:
      - image: oam-dev/service-injector:v1
        name: manager
        command:
        - /app/manager
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        ports:
        - containerPort: 8443
          name: webhook
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-ns-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: service-injector
  labels:
    app: service-injector
webhooks:
  - name: service-injector.default.svc.cluster.local
    clientConfig:
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      # caBundle is the CA cert that sign the webhook's serving cert
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EUXlOekEwTWpZMU9Gb1hEVEk1TURReU5UQTBNalkxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS29rCm4venBLZ2gvR1o2a3ZLRmJ6R25XTTdpc2l0UVVIUXB2WTZicTgycG16am5hZHZYazgrQnQvcUhOWEk1UVZHb1QKN0d6WG90SGxlVFZyM0VVR3llTFdpdW5xYnRsRDJSeUhZTmhEcC85bXRLRkpSUTJ2eFp2ZnZXbnR3bW9vNS9NbwphSmR6T3RJMVJsU0VvM05QclBkRG8yN250VHJNVnprRXBTbHkxSTZRbUNNb2hBdUdTQ3RuZjQ2eUpGUEhibnF0Cm9vSEprZnBsWkxTS2pJUGVZbUJmRTZtREJMS0FiN0JFcTFGT0tPeWFqcnhyUkw1OEVFcm9vMkowa3lDWnJmQXEKRlhybzN6dFpUMTg0cC9aTjF5VWRQeHMxalJMYzIwQ210a2VBcXpuMkZUZ1JKK3o0bVR3N2dOSDZkNHBQY1I3WQpCMzRhVUpkejFxTWdMMlJqRXZVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBblAwQWFnUERnUUtydXU2b3h2cnpiRU93SkN4UWNiVlppSWE2WktmaUEyU0VremhzYQp1Vlc3bUhrQ1ZPOEltWTkrVXVVdXZwYUlpekQ0V28vdjRyUHdySlNDYkdGby84Kys3cXdFS3piMExSdlE2VjJ0ClpOcW9yd2tuZ3BtOFhjaVFWVUdJSmVuYk5LSnF5elpqemhlRXo1Y0U0dXJLWk16ckkwSEhVMVVCZ2pDS00xWGIKODdveVB5bmJIdVJmRlRhbk9nMjlzVXI1QU9iNEFtQTAzUTM2MU1lSG4yWjJKcTR2VkZOUjVQcllJeldEeWNBYQpOL2tBTC9vOU9EOVBWUnNONHR5ZGtqeVRtZkxrUFZUclo3VElSd3RkaG83am96R2xJUDR5L0QzZFUxZmxUSlFyCmVIQkViUmlrelV5UzdlSDNPb1c1eVV1UlhyaERWWGtKVHF5dQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: service-injector
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["statefulsets"]

