apiVersion: core.oam.dev/v1alpha1
kind: ServiceBinding
metadata:
  name: servicebinding-sample
spec:
  bindings:
    - from:
        secret:
          name: my-secret
      to:
        env: true
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busybox1