apiVersion: core.oam.dev/v1alpha1
kind: ServiceBinding
metadata:
  name: servicebinding-sample
spec:
  bindings:
    - from:
        secret:
          name: my-secret
        # volume:
        #   pvcName: nas-pvc
      to:
        env: true
        # filePath: /data
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busybox1