# permissions to do viewer servicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicebinding-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - servicebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - servicebindings/status
  verbs:
  - get
