apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}
data:
  service-injector.key: {{ .Values.secret.injectorKey }}
  service-injector.pem: {{ .Values.secret.injectorCrt }}
type: Opaque
